### ISSUE TITLE
Build sequence issue

### ISSUE THREAD

**Issue by pierre-vigier** [pierre-vigier/Perl6-AttrX-PrivateAccessor#3]
Even if doing its job in this state for basic class, there's a big issue in that module, right now.
If in one class, i have a private method 'plop' , and a private attribute $!plop , using the trait should complain about already having a private method, accessor can't be created. Instead, the private method for the attribute method is created, and when arriving to the private method, it trigger an Exception, as if there was 2 privates methods with the same name (standard exception).

Reason seems to be, that, at the time the trait is creating the method, the meta method ^private_method_table does not contain yet the real private method.

That same problem appears with role, where, method from the role is not found, and the one in the class is then created, which then take precedence one the role's one. It should be alerting, at least when role is applied at compile time, and not dynamically.

Resolution plan:
Use the same strategy as used in AttrX::InitArg, the trait would apply a role to each attribute with the trait, and another role to the class. At compose time for the class, the role will then search for attribute having the attribute role, and create method that point in time, where hopefully private method are already in the private method table.
If a private method in the class has the same name, it should get find, problem might be role composition order

**Comment by pierre-vigier** [comment]
Unfortunately, the Role solution used for Attr::InitArg does not work.
I was working well when i was checking if the private method was created by introspection, however,
calling the private method within a method of the class is crashing. The private accessor is not created soon enough, hence a compilation error :/

**Comment by LLFourn** [comment]
https://github.com/pierre-vigier/Perl6-AttrX-PrivateAccessor/blob/master/lib/AttrX/PrivateAccessor.pm6#L6
This is wrong. Should be:

``` perl6
$class.^private_method_table.first(*.name eq $name)
```

just FYI :)

**Comment by pierre-vigier** [comment]
Hum strange, private_method_table is returning a hash from the doc:
http://doc.perl6.org/routine/private_method_table
and smart matching on a hash should return true if the key exists. Example:

``` perl6
my %hash = key1 => 'value1', key2 => 'value2';

for <key1 key2 key3> -> $k {
    if $k ~~ %hash {
        say "$k is in the hash";
    } else {
        say "$k is in not the hash";
    }
}
```

which prints:

```
key1 is in the hash
key2 is in the hash
key3 is in not the hash
```

If you have more insight on why it would not work with `^private_method_table`, it would be nice

Cheers

**Comment by LLFourn** [comment]
Ah yep my bad :-1: . I forgot it's a hash. And I also just learnt that you can do $key ~~ Hash. I had no idea, thanks for teaching me. I'll try and think of something useful to contribute and get back to you.

**Comment by pierre-vigier** [comment]
For the ~~ on a hash, i take it from there:
https://learnxinyminutes.com/docs/perl6/
in section Equality checking, however, i did not see anything in the doc
about that specifically

**Comment by LLFourn** [comment]
Ok I have something useful. Your issue is that the thing you need to be hooking is type compose time rather than object build time. Try working off this instead:

``` perl6
unit module AttrX::PrivateAccessor:ver<v0.0.1>:auth<github:pierre-vigier>;

my role PrivateAccessor { }

my role PrivateAccessorContainerHOW {
    method compose(Mu \type) {
        for type.^attributes.grep(PrivateAccessor) -> $attr {
            my $name = $attr.name.substr(2); #drop the initial $!
            if $name ~~ type.^private_method_table {
                die "A private method with attribute name already exists, can't create private accessor";
            }

            type.^add_private_method($name, method (Mu:D:) {
                                              $attr.get_value( self );
                                        });

        }
        callsame;
    }
}

multi trait_mod:<is>(Attribute:D $attr, :$providing-private-accessor! ) is export {
    my $class := $attr.package;
    $attr does PrivateAccessor;
    unless $class.HOW ~~ PrivateAccessorContainerHOW {
        $class.HOW does PrivateAccessorContainerHOW
    }
}
```

I test with

``` perl6
use AttrX::PrivateAccessor;


class Foo {
    has $!x is providing-private-accessor = "win";
    has $!y is providing-private-accessor = "win2";
    method foo { self!x }
    method bar { self!y }
}
my $foo = Foo.new;
note $foo.foo;
note $foo.bar;
```

and it works :)

**Comment by pierre-vigier** [comment]
nice,  I was trying to play with meta model how, to analyse a bit before
development,  but it seems you provided a viable solution

**Comment by LLFourn** [comment]
You should probably change the names. They are not very good on second glance. I've no idea if that will work inside roles, but there should be some way to do it.

Also I would prefer the name `is accessible` as `is providing-private-accessor` is a tad long for me :)

**Comment by pierre-vigier** [comment]
Thank you for the tips.
After some other modifications, i finally managed to pass all my tests
